data = [
    { name = 'a', type = 'usize', copy = true },
    { name = 'b', type = 'String' },
]

cells = [
    { name = 'inventory', type = 'Vec<u64>' },
    { name = 'knowledge', type = 'Vec<String>' },
]

flags = [
    { name = 'solid' },
    { name = 'opaque' },
    { name = 'collider' },
]
